INSERT INTO blogful_articles (id, title, date_published, content)
VALUES
  (1, 'First post!', now() - '21 days'::INTERVAL,
    'Here is some content.'),
  (2, 'Second post!', now() - '20 days'::INTERVAL,
    'Here is some content.'),
  (3, 'Third post!', now() - '19 days'::INTERVAL,
    'Here is some content.'),  
  (4, 'Fourth post!', now() - '16 days'::INTERVAL,
    'Here is some content.'),
  (5, 'Fifth post!', now() - '15 days'::INTERVAL,
    'Here is some content.'),
  (6, 'Sixth post!', now() - '14 days'::INTERVAL,
    'Here is some content.'),
  (7, 'Seventh post!', now() - '13 days'::INTERVAL,
    'Here is some content.'),
  (8, 'Eighth post!', now() - '12 days'::INTERVAL,
    'Here is some content.'),
  (9, 'Ninth post!', now() - '12 days'::INTERVAL,
    'Here is some content.'),
  (10, 'Tenth post!', now() - '10 days'::INTERVAL,
    'Here is some content.'),
  (11, 'Eleventh post!', now() - '7 days'::INTERVAL,
    'Here is some content.'),
  (12, 'Twelfth post!', now() - '7 days'::INTERVAL,
    'Here is some content.'),
  (13, 'Thirteenth post!', now() - '6 days'::INTERVAL,
    'Here is some content.'),
  (14, 'Fourteenth post!', now() - '5 days'::INTERVAL,
    'Here is some content.'),
  (15, 'Fifteenth post!', now() - '4 days'::INTERVAL,
    'Here is some content.'),
  (16, 'Sixteenth post!', now() - '3 days'::INTERVAL,
    'Here is some content.'),
  (17, 'Seventeenth post!', now() - '2 days'::INTERVAL,
    'Here is some content.'),
  (18, 'Eighteenth post!', now() - '1 days'::INTERVAL,
    'Here is some content.'),
  (19, 'Nineteenth post!', now(),
    'Here is some content.'),
  (20, 'Twentieth post!', now(),
    'Here is some content.');
